<?php
/**
 * @package    phocaguestbook
 * @subpackage Views
 * @copyright  Copyright (C) 2012 Jan Pavelka www.phoca.cz
 * @license    http://www.gnu.org/copyleft/gpl.html GNU/GPL
 */
defined('_JEXEC') or die('Restricted access');
?>
ONLY DEBUG!!
			
<br><?php echo __LINE__;?>
 <i class="icon-home"></i> (icon-home)
<br><?php echo __LINE__;?>
 <i class="icon-user"></i> (icon-user)
<br><?php echo __LINE__;?>
 <i class="icon-checkedout"></i> (icon-checkedout)
<br><?php echo __LINE__;?>
 <i class="icon-lock"></i> (icon-lock)
<br><?php echo __LINE__;?>
 <i class="icon-locked"></i> (icon-locked)
<br><?php echo __LINE__;?>
 <i class="icon-comment"></i> (icon-comment)
<br><?php echo __LINE__;?>
 <i class="icon-comments"></i> (icon-comments)
<br><?php echo __LINE__;?>
 <i class="icon-comments-2"></i> (icon-comments-2)
<br><?php echo __LINE__;?>
 <i class="icon-share-alt"></i> (icon-share-alt)
<br><?php echo __LINE__;?>
 <i class="icon-out"></i> (icon-out)
<br><?php echo __LINE__;?>
 <i class="icon-share"></i> (icon-share)
<br><?php echo __LINE__;?>
 <i class="icon-redo"></i> (icon-redo)
<br><?php echo __LINE__;?>
 <i class="icon-undo"></i> (icon-undo)
<br><?php echo __LINE__;?>
 <i class="icon-file-add"></i> (icon-file-add)
<br><?php echo __LINE__;?>
 <i class="icon-new"></i> (icon-new)
<br><?php echo __LINE__;?>
 <i class="icon-plus"></i> (icon-plus)
<br><?php echo __LINE__;?>
 <i class="icon-apply"></i> (icon-apply)
<br><?php echo __LINE__;?>
 <i class="icon-edit"></i> (icon-edit)
<br><?php echo __LINE__;?>
 <i class="icon-pencil"></i> (icon-pencil)
<br><?php echo __LINE__;?>
 <i class="icon-pencil-2"></i> (icon-pencil-2)
<br><?php echo __LINE__;?>
 <i class="icon-folder"></i> (icon-folder)
<br><?php echo __LINE__;?>
 <i class="icon-folder-2"></i> (icon-folder-2)
<br><?php echo __LINE__;?>
 <i class="icon-picture"></i> (icon-picture)
<br><?php echo __LINE__;?>
 <i class="icon-pictures"></i> (icon-pictures)
<br><?php echo __LINE__;?>
 <i class="icon-list"></i> (icon-list)
<br><?php echo __LINE__;?>
 <i class="icon-list-view"></i> (icon-list-view)
<br><?php echo __LINE__;?>
 <i class="icon-power-cord"></i> (icon-power-cord)
<br><?php echo __LINE__;?>
 <i class="icon-cube"></i> (icon-cube)
<br><?php echo __LINE__;?>
 <i class="icon-puzzle"></i> (icon-puzzle)
<br><?php echo __LINE__;?>
 <i class="icon-flag"></i> (icon-flag)
<br><?php echo __LINE__;?>
 <i class="icon-tools"></i> (icon-tools)
<br><?php echo __LINE__;?>
 <i class="icon-cogs"></i> (icon-cogs)
<br><?php echo __LINE__;?>
 <i class="icon-options"></i> (icon-options)
<br><?php echo __LINE__;?>
 <i class="icon-cog"></i> (icon-cog)
<br><?php echo __LINE__;?>
 <i class="icon-equalizer"></i> (icon-equalizer)
<br><?php echo __LINE__;?>
 <i class="icon-wrench"></i> (icon-wrench)
<br><?php echo __LINE__;?>
 <i class="icon-brush"></i> (icon-brush)
<br><?php echo __LINE__;?>
 <i class="icon-eye-open"></i> (icon-eye-open)
<br><?php echo __LINE__;?>
 <i class="icon-eye"></i> (icon-eye)
<br><?php echo __LINE__;?>
 <i class="icon-checkbox-unchecked"></i> (icon-checkbox-unchecked)
<br><?php echo __LINE__;?>
 <i class="icon-checkin"></i> (icon-checkin)
<br><?php echo __LINE__;?>
 <i class="icon-checkbox"></i> (icon-checkbox)
<br><?php echo __LINE__;?>
 <i class="icon-checkbox-partial"></i> (icon-checkbox-partial)
<br><?php echo __LINE__;?>
 <i class="icon-asterisk"></i> (icon-asterisk)
<br><?php echo __LINE__;?>
 <i class="icon-star-empty"></i> (icon-star-empty)
<br><?php echo __LINE__;?>
 <i class="icon-star-2"></i> (icon-star-2)
<br><?php echo __LINE__;?>
 <i class="icon-featured"></i> (icon-featured)
<br><?php echo __LINE__;?>
 <i class="icon-star"></i> (icon-star)
<br><?php echo __LINE__;?>
 <i class="icon-calendar"></i> (icon-calendar)
<br><?php echo __LINE__;?>
 <i class="icon-calendar-2"></i> (icon-calendar-2)
<br><?php echo __LINE__;?>
 <i class="icon-question-sign"></i> (icon-question-sign)
<br><?php echo __LINE__;?>
 <i class="icon-help"></i> (icon-help)
<br><?php echo __LINE__;?>
 <i class="icon-support"></i> (icon-support)
<br><?php echo __LINE__;?>
 <i class="icon-warning"></i> (icon-warning)
<br><?php echo __LINE__;?>
 <i class="icon-publish"></i> (icon-publish)
<br><?php echo __LINE__;?>
 <i class="icon-save"></i> (icon-save)
<br><?php echo __LINE__;?>
 <i class="icon-ok"></i> (icon-ok)
<br><?php echo __LINE__;?>
 <i class="icon-checkmark"></i> (icon-checkmark)
<br><?php echo __LINE__;?>
 <i class="icon-unpublish"></i> (icon-unpublish)
<br><?php echo __LINE__;?>
 <i class="icon-trash"></i> (icon-trash)
<br><?php echo __LINE__;?>
 <i class="icon-cancel"></i> (icon-cancel)
<br><?php echo __LINE__;?>
 <i class="icon-eye-close"></i> (icon-eye-close)
<br><?php echo __LINE__;?>
 <i class="icon-minus"></i> (icon-minus)
<br><?php echo __LINE__;?>
 <i class="icon-purge"></i> (icon-purge)
<br><?php echo __LINE__;?>
 <i class="icon-trash"></i> (icon-trash)
<br><?php echo __LINE__;?>
 <i class="icon-envelope"></i> (icon-envelope)
<br><?php echo __LINE__;?>
 <i class="icon-mail"></i> (icon-mail)
<br><?php echo __LINE__;?>
 <i class="icon-mail-2"></i> (icon-mail-2)
<br><?php echo __LINE__;?>
 <i class="icon-unarchive"></i> (icon-unarchive)
<br><?php echo __LINE__;?>
 <i class="icon-drawer"></i> (icon-drawer)
<br><?php echo __LINE__;?>
 <i class="icon-archive"></i> (icon-archive)
<br><?php echo __LINE__;?>
 <i class="icon-drawer-2"></i> (icon-drawer-2)
<br><?php echo __LINE__;?>
 <i class="icon-box-add"></i> (icon-box-add)
<br><?php echo __LINE__;?>
 <i class="icon-box-remove"></i> (icon-box-remove)
<br><?php echo __LINE__;?>
 <i class="icon-search"></i> (icon-search)
<br><?php echo __LINE__;?>
 <i class="icon-filter"></i> (icon-filter)
<br><?php echo __LINE__;?>
 <i class="icon-camera"></i> (icon-camera)
<br><?php echo __LINE__;?>
 <i class="icon-play"></i> (icon-play)
<br><?php echo __LINE__;?>
 <i class="icon-music"></i> (icon-music)
<br><?php echo __LINE__;?>
 <i class="icon-grid-view"></i> (icon-grid-view)
<br><?php echo __LINE__;?>
 <i class="icon-grid-view-2"></i> (icon-grid-view-2)
<br><?php echo __LINE__;?>
 <i class="icon-menu"></i> (icon-menu)
<br><?php echo __LINE__;?>
 <i class="icon-thumbs-up"></i> (icon-thumbs-up)
<br><?php echo __LINE__;?>
 <i class="icon-thumbs-down"></i> (icon-thumbs-down)
<br><?php echo __LINE__;?>
 <i class="icon-delete"></i> (icon-delete)
<br><?php echo __LINE__;?>
 <i class="icon-remove"></i> (icon-remove)
<br><?php echo __LINE__;?>
 <i class="icon-cancel-2"></i> (icon-cancel-2)
<br><?php echo __LINE__;?>
 <i class="icon-save-new"></i> (icon-save-new)
<br><?php echo __LINE__;?>
 <i class="icon-plus-2"></i> (icon-plus-2)
<br><?php echo __LINE__;?>
 <i class="icon-ban-circle"></i> (icon-ban-circle)
<br><?php echo __LINE__;?>
 <i class="icon-minus-sign"></i> (icon-minus-sign)
<br><?php echo __LINE__;?>
 <i class="icon-minus-2"></i> (icon-minus-2)
<br><?php echo __LINE__;?>
 <i class="icon-key"></i> (icon-key)
<br><?php echo __LINE__;?>
 <i class="icon-quote"></i> (icon-quote)
<br><?php echo __LINE__;?>
 <i class="icon-quote-2"></i> (icon-quote-2)
<br><?php echo __LINE__;?>
 <i class="icon-database"></i> (icon-database)
<br><?php echo __LINE__;?>
 <i class="icon-location"></i> (icon-location)
<br><?php echo __LINE__;?>
 <i class="icon-zoom-in"></i> (icon-zoom-in)
<br><?php echo __LINE__;?>
 <i class="icon-zoom-out"></i> (icon-zoom-out)
<br><?php echo __LINE__;?>
 <i class="icon-expand"></i> (icon-expand)
<br><?php echo __LINE__;?>
 <i class="icon-contract"></i> (icon-contract)
<br><?php echo __LINE__;?>
 <i class="icon-expand-2"></i> (icon-expand-2)
<br><?php echo __LINE__;?>
 <i class="icon-contract-2"></i> (icon-contract-2)
<br><?php echo __LINE__;?>
 <i class="icon-health"></i> (icon-health)
<br><?php echo __LINE__;?>
 <i class="icon-wand"></i> (icon-wand)
<br><?php echo __LINE__;?>
 <i class="icon-unblock"></i> (icon-unblock)
<br><?php echo __LINE__;?>
 <i class="icon-refresh"></i> (icon-refresh)
<br><?php echo __LINE__;?>
 <i class="icon-vcard"></i> (icon-vcard)
<br><?php echo __LINE__;?>
 <i class="icon-clock"></i> (icon-clock)
<br><?php echo __LINE__;?>
 <i class="icon-compass"></i> (icon-compass)
<br><?php echo __LINE__;?>
 <i class="icon-address"></i> (icon-address)
<br><?php echo __LINE__;?>
 <i class="icon-feed"></i> (icon-feed)
<br><?php echo __LINE__;?>
 <i class="icon-flag-2"></i> (icon-flag-2)
<br><?php echo __LINE__;?>
 <i class="icon-pin"></i> (icon-pin)
<br><?php echo __LINE__;?>
 <i class="icon-lamp"></i> (icon-lamp)
<br><?php echo __LINE__;?>
 <i class="icon-chart"></i> (icon-chart)
<br><?php echo __LINE__;?>
 <i class="icon-bars"></i> (icon-bars)
<br><?php echo __LINE__;?>
 <i class="icon-pie"></i> (icon-pie)
<br><?php echo __LINE__;?>
 <i class="icon-dashboard"></i> (icon-dashboard)
<br><?php echo __LINE__;?>
 <i class="icon-lightning"></i> (icon-lightning)
<br><?php echo __LINE__;?>
 <i class="icon-move"></i> (icon-move)
<br><?php echo __LINE__;?>
 <i class="icon-next"></i> (icon-next)
<br><?php echo __LINE__;?>
 <i class="icon-previous"></i> (icon-previous)
<br><?php echo __LINE__;?>
 <i class="icon-first"></i> (icon-first)
<br><?php echo __LINE__;?>
 <i class="icon-last"></i> (icon-last)
<br><?php echo __LINE__;?>
 <i class="icon-loop"></i> (icon-loop)
<br><?php echo __LINE__;?>
 <i class="icon-shuffle"></i> (icon-shuffle)
<br><?php echo __LINE__;?>
 <i class="icon-arrow-first"></i> (icon-arrow-first)
<br><?php echo __LINE__;?>
 <i class="icon-arrow-last"></i> (icon-arrow-last)
<br><?php echo __LINE__;?>
 <i class="icon-chevron-up"></i> (icon-chevron-up)
<br><?php echo __LINE__;?>
 <i class="icon-uparrow"></i> (icon-uparrow)
<br><?php echo __LINE__;?>
 <i class="icon-arrow-up"></i> (icon-arrow-up)
<br><?php echo __LINE__;?>
 <i class="icon-chevron-right"></i> (icon-chevron-right)
<br><?php echo __LINE__;?>
 <i class="icon-arrow-right"></i> (icon-arrow-right)
<br><?php echo __LINE__;?>
 <i class="icon-chevron-down"></i> (icon-chevron-down)
<br><?php echo __LINE__;?>
 <i class="icon-downarrow"></i> (icon-downarrow)
<br><?php echo __LINE__;?>
 <i class="icon-arrow-down"></i> (icon-arrow-down)
<br><?php echo __LINE__;?>
 <i class="icon-chevron-left"></i> (icon-chevron-left)
<br><?php echo __LINE__;?>
 <i class="icon-arrow-left"></i> (icon-arrow-left)
<br><?php echo __LINE__;?>
 <i class="icon-arrow-up-2"></i> (icon-arrow-up-2)
<br><?php echo __LINE__;?>
 <i class="icon-arrow-right-2"></i> (icon-arrow-right-2)
<br><?php echo __LINE__;?>
 <i class="icon-download"></i> (icon-download)
<br><?php echo __LINE__;?>
 <i class="icon-arrow-down-2"></i> (icon-arrow-down-2)
<br><?php echo __LINE__;?>
 <i class="icon-arrow-left-2"></i> (icon-arrow-left-2)
<br><?php echo __LINE__;?>
 <i class="icon-play-2"></i> (icon-play-2)
<br><?php echo __LINE__;?>
 <i class="icon-menu-2"></i> (icon-menu-2)
<br><?php echo __LINE__;?>
 <i class="icon-arrow-up-3"></i> (icon-arrow-up-3)
<br><?php echo __LINE__;?>
 <i class="icon-arrow-right-3"></i> (icon-arrow-right-3)
<br><?php echo __LINE__;?>
 <i class="icon-arrow-down-3"></i> (icon-arrow-down-3)
<br><?php echo __LINE__;?>
 <i class="icon-arrow-left-3"></i> (icon-arrow-left-3)
<br><?php echo __LINE__;?>
 <i class="icon-print"></i> (icon-print)
<br><?php echo __LINE__;?>
 <i class="icon-printer"></i> (icon-printer)
<br><?php echo __LINE__;?>
 <i class="icon-color-palette"></i> (icon-color-palette)
<br><?php echo __LINE__;?>
 <i class="icon-camera-2"></i> (icon-camera-2)
<br><?php echo __LINE__;?>
 <i class="icon-file"></i> (icon-file)
<br><?php echo __LINE__;?>
 <i class="icon-file-remove"></i> (icon-file-remove)
<br><?php echo __LINE__;?>
 <i class="icon-save-copy"></i> (icon-save-copy)
<br><?php echo __LINE__;?>
 <i class="icon-copy"></i> (icon-copy)
<br><?php echo __LINE__;?>
 <i class="icon-cart"></i> (icon-cart)
<br><?php echo __LINE__;?>
 <i class="icon-basket"></i> (icon-basket)
<br><?php echo __LINE__;?>
 <i class="icon-broadcast"></i> (icon-broadcast)
<br><?php echo __LINE__;?>
 <i class="icon-screen"></i> (icon-screen)
<br><?php echo __LINE__;?>
 <i class="icon-tablet"></i> (icon-tablet)
<br><?php echo __LINE__;?>
 <i class="icon-mobile"></i> (icon-mobile)
<br><?php echo __LINE__;?>
 <i class="icon-users"></i> (icon-users)
<br><?php echo __LINE__;?>
 <i class="icon-briefcase"></i> (icon-briefcase)
<br><?php echo __LINE__;?>
 <i class="icon-download"></i> (icon-download)
<br><?php echo __LINE__;?>
 <i class="icon-upload"></i> (icon-upload)
<br><?php echo __LINE__;?>
 <i class="icon-bookmark"></i> (icon-bookmark)
<br><?php echo __LINE__;?>
 <i class="icon-out-2"></i> (icon-out-2)
